### ISSUE TITLE
step.while() no longer working

### ISSUE THREAD

**Issue by angrygreenfrogs** [flood-io/element#314]
I'm using the latest Element as from today 1.3.8 (yarn global upgrade element-cli)

step.while() runs once but does not repeat

Reproducible even using the example code from Github:

https://github.com/flood-io/element/blob/master/examples/condition/test.ts

```
element run test.ts
+62s info: ===> Step 'Step 5'
Step 5
+62s info: ---> Step 'Step 5' finished in 1ms
```

The text "Step 5" should be output 3 times from the example code, but it's only output once.

**Comment by phileba** [comment]
thank @angrygreenfrogs , we will have a look at this

**Comment by cjpablo92** [comment]
In version 1.3.9 is not working either...do you have any plan on fixing this? unless is not working either

**Comment by phileba** [comment]
Hi @cjpablo92, we plan to release a fix in version 1.4. But this issue has been fixed in the latest element beta.

**Comment by cjpablo92** [comment]
> Hi @cjpablo92, we plan to release a fix in version 1.4. But this issue has been fixed in the latest element beta.

Great Thanks!

**Comment by dnch** [comment]
What's the status of this fix? I'm using 2.0.4 and still getting this behaviour.

 I found #333 but can't see any sign of it in `beta` or `canary`

**Comment by fhitb** [comment]
Same for me in 2.0.4 - step.while runs once, but does not repeat (even with `() => true` as condition).
