### ISSUE TITLE
UPDATE AVAILABLE prevent scripts from running and update is invalid

### ISSUE THREAD

**Issue by aviationfan** [flood-io/element#83]
When I tried to run a script at the command line element exited and reported that an update was available. When I tried to update nothing happened because I already have the latest version. This update message stops me from using the `element run` command

**To Reproduce**
1. Run a simple script the normal way `element run flooded_io.ts`
2. Message comes back
```
> 'UPDATE AVAILABLE' The latest   version of Element CLI is 1.0.8-stable.1
> Get it by running brew upgrade element
+0s info: workRootPath: /Users/jjwelch/Dropbox/PeoplesUnited/element_poc_oao/new-account-flow-oao/tmp/element-results/flooded_io/2019-09-05T163319.696Z
+0s info: testDataPath: /Users/jjwelch/Dropbox/PeoplesUnited/element_poc_oao/new-account-flow-oao
> Error! An unexpected empty rejection occurred
 rejection: null
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md
```
3. Try to upgrade element
```
brew upgrade element
Error: flood-io/taps/element 1.0.8 already installed
```
4. Check my version
```
element --version
> 'UPDATE AVAILABLE' The latest   version of Element CLI is 1.0.8-stable.1
> Get it by running brew upgrade element
1.0.8
```

**Expected behavior**
Element should run no matter what version I have. Why does it not support using an older version? Why does it stop me from running due to an update available? How do I override and run it until this brew issue is fixed?

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 High Sierra
 - node --version v12.9.1
 - npm --version 6.11.2
 - lighthouse --version 5.1.0

**Additional context**
Is this a conflict with NPM? I have NPM so I can run google lighthouse at the command line. Of course, it has been working with NPM and Lighthouse for weeks so I doubt that is it.

I think this is a config problem with homebrew at the source

**Comment by aviationfan** [comment]
I cannot even make a new project using element

```
element init oao-peoples
> 'UPDATE AVAILABLE' The latest   version of Element CLI is 1.0.8-stable.1
> Get it by running brew upgrade element
initting into /Users/jjwelch/customers/PeoplesUnited/oao-peoples
? The title of this test. (oao-peoples) > Error! An unexpected empty rejection occurred
 rejection: null
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md
```
This is really frustrating

**Comment by ivanvanderbyl** [comment]
@aviationfan thanks for reporting. We're working on a fix for this ASAP.

**Comment by ivanvanderbyl** [comment]
This should now be fixed on the latest beta, please give it a try by upgrading to `@flood/element-cli@beta`

**Comment by GamesmenJordan** [comment]
This bug is seemingly not resolved.

Due to the bug with 2.0.4 not being able to run scripts at all (https://github.com/flood-io/element/issues/540) I attempted to downgrade progressively each version (2.0.3, 2.0.2, 2.0.1, 2.0.0) and all of these versions throw this same error `Error! An unexpected empty rejection occurred rejection: null`

So a combination of a current version that is broken and can't run any scripts and a broken update checker script that throws error that prevents me running older versions that potentially should work means the entire toolset is completely unusable?
