### ISSUE TITLE
Distribution Tag Stable is Not Available

### ISSUE THREAD

**Issue by jladaban** [flood-io/element#90]
**Describe the bug**
Checking for failed updates failed.

**To Reproduce**
1. Go to Terminal and run element --version
2. I get the following messages:
```
> Error! Checking for updates failed
Error: Distribution tag stable is not available
    at getMostRecent (/usr/local/lib/node_modules/@flood/element-cli/node_modules/update-check/index.js:140:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/usr/local/lib/node_modules/@flood/element-cli/node_modules/update-check/index.js:185:12)
    at async doUpdateCheck (/usr/local/lib/node_modules/@flood/element-cli/dist/src/element.js:71:24)
    at async Object.main (/usr/local/lib/node_modules/@flood/element-cli/dist/src/element.js:40:5)
1.0.8-stable.1
```

**Expected behavior**
Should not have error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Node.js version: unknown
 - Element 1.0.8

**Comment by Sheep42** [comment]
I have the same issue on Windows. Reported it to support about a month ago. Unfortunately element bails after the error is thrown and it prevents me from running tests locally.

OS: Windows 10
Node.js Version: 12.13.1
Element: 1.0.8

I've also tried using a few older versions of Node with no luck.

**Comment by ivanvanderbyl** [comment]
Hi  @jladaban @Sheep42  — we're aware of this issue, it is resolved on the latest beta, and will be promoted to stable once we resolve a Windows path issue blocking the current build.

**Install beta**


NPM:
```
npm install -g @flood/element-cli@beta
```

Yarn:
```
yarn global add @flood/element-cli@beta
```

**Comment by dorrogeray** [comment]
I can confirm the issue is still present, installing beta helped. Node 12.13, Ubuntu 18.04 LTS.

**Comment by Sheep42** [comment]
@ivanvanderbyl Thanks for the update, I can confirm on Windows installing beta fixes this issue for me.
